#!/usr/bin/env php

<?php
\ini_set("memory_limit", "1536M");
\ini_set("display_errors", 1);

include_once(__DIR__ . \DIRECTORY_SEPARATOR . "everdio.php");

$cli = new \Component\Core\Controller\Model\Cli;
$cli->server = $_SERVER;
$cli->path = __DIR__;
$cli->debug = "_debug";
$cli->setup();

$cli->echo("Everdio Commandline", ["bright", "green", "underline"], 2);
if (!isset($cli->execute)) {
    $cli->echo("Nothing to execute", ["red"], 2);
    exit;
}

$cli->echo(\sprintf("Processing `%s` with pid ", $cli->execute), ["white", "blackbg", "bright"], 0);
$cli->echo(\sprintf("`%s`", $cli->pid), ["green"], 2);

try {
    $cli->execute(\DIRECTORY_SEPARATOR . $cli->execute);
} catch (\Exception $ex) {
    if (isset($cli->request->{$cli->debug})) {
        throw new \RuntimeException($ex->getMessage(), 0, $ex);
    }

    $cli->echo($ex->getMessage(), ["red", "blackbg"], 2);
}

$cli->echo(\sprintf("Processed in %ss with %s memory consumption", $cli->getTime(), $cli->getSizeformat(\memory_get_peak_usage(true))), ["bright", "yellow"], 2);
exit;