#!/usr/bin/env php

<?php
\ini_set("memory_limit", "1536M");
\ini_set("display_errors", 1);

include_once(__DIR__ . \DIRECTORY_SEPARATOR . "everdio.php");

$cli = new \Component\Core\Controller\Model\Cli;
$cli->server = $_SERVER;
$cli->path = __DIR__;
$cli->setup();

try {
    echo $cli->execute(\DIRECTORY_SEPARATOR . $cli->route) . \PHP_EOL;
} catch (\RuntimeException $ex) {
    if (isset($cli->request->_debug)) {
        throw $ex;
    }
    echo \sprintf("Everdio: %s\n\n", $ex->getMessage());
}
exit;